// The door's permission records (WHAT'S LEFT D7, 2026-10-02).
//
// The tool server's tools declared what they are -- writes or reads, which actions of a writing tool
// only read, which arguments are secrets, what they need beyond a directory -- and the shipped role
// policy decided who may call what, but nothing set the two side by side where the operator could read
// them in one sitting. "The door's tools have no records" was the line; this is the record. It is NOT
// written beside the table and the policy: it is read OFF them, by the same functions that judge a real
// call (rbac.Can, Tool.Writes, Tool.Reads, HeldExempt), so it cannot say something the door does not do.
// A tool added, a flag turned or a role changed makes docs/TOOL_PERMISSIONS.md stale, and a stale copy
// fails here, in review, before the change reaches a door.
//
// WHAT IT DOES NOT CLAIM. A tool's `Writes` flag is its author's declaration. Nothing here proves a tool
// that says it only reads never writes: that is each tool's own test (the jail strokes, the reading-
// action strokes). The record makes a change of declaration VISIBLE; it does not make a false one true.
//
// Regenerate (from atlas/line):
//
//	go test ./internal/tools -run TestEveryToolHasAPermissionRecord -update
//
// Go's test cache does not see a file outside the module (the record is in atlas/docs, the module is
// atlas/line), so after editing the record by hand a repeat of the same command may answer from the
// cache: run it with -count=1. tests/prove.py does, and so does GitHub, which has no cache.
package tools

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"atlas/line/internal/rbac"
	"atlas/line/internal/tenant"
)

var updateRecords = flag.Bool("update", false,
	"rewrite docs/TOOL_PERMISSIONS.md from the tool table (go test ./internal/tools -run TestEveryToolHasAPermissionRecord -update)")

// permissionRoles are the columns, in the order the policy introduces them. A role the policy ships and
// this list lacks fails TestThePermissionRecordNamesEveryShippedRole: a record that silently left a role
// out would be the promise-not-checked this file exists to refuse.
var permissionRoles = []string{"operator", "steward", "agent", "guest"}

// permissionCell is what one role is told about one tool, asked of rbac.Can the way a call is: `yes`
// when the whole tool is allowed, `reads only` when the role is refused the tool as a writer but may call
// its reading actions (git_tag list), `-` when it is refused.
func permissionCell(p rbac.Policy, role string, t Tool) string {
	if full, _, _ := rbac.Can(p, role, t.Name, t.Writes); full {
		return "yes"
	}
	if t.Writes && len(t.Reads) > 0 {
		if r, _, _ := rbac.Can(p, role, t.Name, false); r {
			return "reads only"
		}
	}
	return "-"
}

func dash(s string) string {
	if strings.TrimSpace(s) == "" {
		return "-"
	}
	return s
}

// renderToolPermissions is the whole record, from the table and the shipped policy and nothing else.
func renderToolPermissions(reg *Registry) string {
	pol := rbac.DefaultPolicy()
	for _, r := range permissionRoles {
		if err := rbac.AssignAgent(&pol, r, r); err != nil {
			panic(err) // a role the policy does not ship: caught by the roles test, loudly
		}
	}
	tools := reg.All()
	sort.Slice(tools, func(i, j int) bool { return tools[i].Name < tools[j].Name })

	reads, writes, mixed, secrets := 0, 0, 0, 0
	tiers := map[string]int{}
	for _, t := range tools {
		tiers[t.Tier.String()]++
		if t.Writes {
			writes++
			if len(t.Reads) > 0 {
				mixed++
			}
		} else {
			reads++
		}
		if len(t.Secrets) > 0 {
			secrets++
		}
	}

	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }
	w("# THE DOOR'S TOOLS -- what each one declares, and who may call it\n\n")
	w("GENERATED by `go test ./internal/tools -run TestEveryToolHasAPermissionRecord -update` (from `atlas/line`);\n")
	w("never hand-edited. It is read OFF the tool table and the shipped role policy, by the functions that judge a\n")
	w("real call (`rbac.Can`, `Tool.Writes`, `Tool.Reads`, `HeldExempt`), so it cannot say what the door does not\n")
	w("do; and a stale copy fails the test, so a tool added, a flag turned or a role changed shows up in review.\n")
	w("The core's WHAT'S LEFT D7, 2026-10-02.\n\n")
	w("**What it does not claim.** A tool's `Writes` flag is its author's declaration. Nothing here proves a tool\n")
	w("that says it only reads never writes; that is each tool's own test. The record makes a change of\n")
	w("declaration visible. It does not make a false one true.\n\n")
	w("## How a call is judged\n\n")
	w("1. WHO is asking comes from the transport, never from the arguments. The glass (the service wire) is the\n")
	w("   operator's hand and passes. Anything else is judged by the name the door gave it against the tenant's\n")
	w("   role policy (`rbac.Can`): the tool by name, then `*`, then the kinds the call carries -- `tools` always,\n")
	w("   and `edit` for a tool that writes or `read` for one that does not. A tenant with no roles assigned is\n")
	w("   open mode, and says so on every hold record and in the boot line.\n")
	w("2. With the door's `--auth` on, a call that WRITES from anything but the glass is parked as a hold and runs\n")
	w("   only when the operator approves it there. `hold_answer` and `hold_list` are exempt: they are how a hold\n")
	w("   is answered and read. A reading action of a writing tool (`git_tag list`) is judged as a read.\n")
	w("3. `can_approve` is structurally false. rbac never grants approval; it lives in the hand alone.\n\n")
	w("## The record\n\n")
	w("%d tools: %d read, %d write (%d of the writers have reading actions); %d carry a secret argument. ",
		len(tools), reads, writes, mixed, secrets)
	w("Tiers: core %d, spine %d, engine %d.\n\n", tiers["core"], tiers["spine"], tiers["engine"])
	w("`yes` = may call it; `reads only` = refused the tool as a writer, may call its reading actions; `-` = refused. ")
	w("`held` = a call from anything but the glass waits for the operator when holds are armed.\n\n")
	w("| tool | tier | declares | reading actions | secret args | held |")
	for _, r := range permissionRoles {
		w(" %s |", r)
	}
	w("\n|---|---|---|---|---|---|")
	for range permissionRoles {
		w("---|")
	}
	w("\n")
	for _, t := range tools {
		declares := "reads"
		held := "-"
		if t.Writes {
			declares = "writes"
			held = "held"
			if HeldExempt(t.Name) {
				held = "exempt"
			}
		}
		w("| `%s` | %s | %s | %s | %s | %s |", t.Name, t.Tier.String(), declares,
			dash(strings.Join(t.Reads, ", ")), dash(strings.Join(t.Secrets, ", ")), held)
		for _, r := range permissionRoles {
			w(" %s |", permissionCell(pol, r, t))
		}
		w("\n")
	}
	return b.String()
}

// firstDifference names the first line two texts part at, so a stale record says where.
func firstDifference(got, want string) string {
	g, w := strings.Split(got, "\n"), strings.Split(want, "\n")
	for i := 0; i < len(g) || i < len(w); i++ {
		var gl, wl string
		if i < len(g) {
			gl = g[i]
		}
		if i < len(w) {
			wl = w[i]
		}
		if gl != wl {
			if len(gl) > 140 {
				gl = gl[:140]
			}
			if len(wl) > 140 {
				wl = wl[:140]
			}
			return fmt.Sprintf("line %d: the file has %q; the table says %q", i+1, gl, wl)
		}
	}
	return "the texts differ in length only"
}

func permissionRecordPath() string {
	return filepath.Join("..", "..", "..", "docs", "TOOL_PERMISSIONS.md")
}

// THE RECORD IS CURRENT. Every tool has a row, and the rows are what the table and the policy say now.
func TestEveryToolHasAPermissionRecord(t *testing.T) {
	reg := Build(tenant.NewRegistry(), Options{HoldWrites: true})
	want := renderToolPermissions(reg)
	path := permissionRecordPath()
	if *updateRecords {
		if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s: %d tools", path, len(reg.All()))
		return
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%s is missing (%v).\n  write it: go test ./internal/tools -run TestEveryToolHasAPermissionRecord -update", path, err)
	}
	got := strings.ReplaceAll(string(raw), "\r\n", "\n")
	if got != want {
		t.Fatalf("docs/TOOL_PERMISSIONS.md is STALE -- %s\n  regenerate: go test ./internal/tools -run TestEveryToolHasAPermissionRecord -update",
			firstDifference(got, want))
	}
}

// THE RECORD NAMES EVERY ROLE THE POLICY SHIPS, and no role the policy does not.
func TestThePermissionRecordNamesEveryShippedRole(t *testing.T) {
	shipped := []string{}
	for name := range rbac.DefaultPolicy().Roles {
		shipped = append(shipped, name)
	}
	sort.Strings(shipped)
	have := append([]string(nil), permissionRoles...)
	sort.Strings(have)
	if strings.Join(shipped, ",") != strings.Join(have, ",") {
		t.Fatalf("the policy ships roles %v and the record has columns for %v: a role the record leaves out "+
			"is a permission nobody can read", shipped, have)
	}
}

// ONE ROW PER TOOL, in the file as it stands.
func TestThePermissionRecordHasOneRowPerTool(t *testing.T) {
	reg := Build(tenant.NewRegistry(), Options{HoldWrites: true})
	raw, err := os.ReadFile(permissionRecordPath())
	if err != nil {
		t.Skipf("no record to read yet: %v", err)
	}
	text := strings.ReplaceAll(string(raw), "\r\n", "\n")
	for _, tool := range reg.All() {
		if n := strings.Count(text, "\n| `"+tool.Name+"` |"); n != 1 {
			t.Errorf("tool %q has %d rows in docs/TOOL_PERMISSIONS.md, want exactly one", tool.Name, n)
		}
	}
}

// THE SHIPPED POLICY SAYS WHAT THE RECORD CLAIMS. Held as facts of the policy, so changing one is a
// decision made on purpose, with these three lines changed beside it.
func TestTheShippedRolesAnswerAsTheRecordSays(t *testing.T) {
	reg := Build(tenant.NewRegistry(), Options{HoldWrites: true})
	pol := rbac.DefaultPolicy()
	for _, r := range permissionRoles {
		if err := rbac.AssignAgent(&pol, r, r); err != nil {
			t.Fatal(err)
		}
	}
	for _, tool := range reg.All() {
		if got := permissionCell(pol, "operator", tool); got != "yes" {
			t.Errorf("the operator's role is refused %s (%s): the operator's hand is absolute", tool.Name, got)
		}
		if got := permissionCell(pol, "guest", tool); got != "-" {
			t.Errorf("the guest role may call %s (%s): guest is unauthenticated and denied all", tool.Name, got)
		}
		if tool.Writes && len(tool.Reads) == 0 {
			if got := permissionCell(pol, "agent", tool); got != "-" {
				t.Errorf("the agent role may call %s (%s), a tool that only writes: every tool that writes is denied it by kind",
					tool.Name, got)
			}
		}
	}
}
